name: Docker

on:
  push:
    branches:
    - master
    - rose/core-2000
    tags: ["v*"]

jobs:
  publish:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - uses: docker/build-push-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
          registry: ghcr.io
          repository: dafnifacility/plotter/web
          tags: latest
          tag_with_ref: true
